from __future__ import annotations


class SignalAdapter:
    """
    Adapts RuntimeContext produced by LiveEngine into a TradingDecision
    consumable by the Backtesting TradingPipeline.

    This class intentionally contains NO trading logic.

    Responsibilities
    ----------------
    • Read RuntimeContext
    • Extract the latest TradingDecision
    • Validate availability
    • Return None when no executable decision exists

    It does NOT:

    • Generate signals
    • Modify decisions
    • Execute trades
    • Calculate analytics
    """

    def __init__(self):
        pass

    # ==========================================================
    # Public API
    # ==========================================================

    def from_context(self, ctx):
        """
        Extract the latest TradingDecision from RuntimeContext.

        Parameters
        ----------
        ctx
            RuntimeContext generated by LiveEngine.

        Returns
        -------
        TradingDecision | None
        """

        if ctx is None:
            return None

        #
        # RuntimeContext structure may evolve.
        #
        # We deliberately use getattr() so the adapter
        # remains backward compatible while RuntimeContext
        # grows.
        #

        decision = getattr(ctx, "decision", None)

        if decision is None:
            return None

        return decision