import streamlit as st

from app.services.live_service import LiveService


def show():
    """
    Trading Performance Dashboard.

    Displays trading statistics generated by
    PerformanceEngine.
    """

    service = LiveService()
    ctx = service.get_context()

    st.title("📈 Performance")

    performance = ctx.performance

    if performance is None:
        st.info("No completed trades available.")
        return

    # ==========================================================
    # TRADE STATISTICS
    # ==========================================================

    st.subheader("Trade Statistics")

    c1, c2, c3, c4 = st.columns(4)

    c1.metric("Total Trades", performance.total_trades)
    c2.metric("Winning", performance.winning_trades)
    c3.metric("Losing", performance.losing_trades)
    c4.metric("Win Rate", f"{performance.win_rate:.2f}%")

    st.divider()

    # ==========================================================
    # PROFIT & LOSS
    # ==========================================================

    st.subheader("Profit & Loss")

    c1, c2, c3 = st.columns(3)

    c1.metric("Gross Profit", f"{performance.gross_profit:.2f}")
    c2.metric("Gross Loss", f"{performance.gross_loss:.2f}")
    c3.metric("Net Profit", f"{performance.net_profit:.2f}")

    st.divider()

    # ==========================================================
    # RISK METRICS
    # ==========================================================

    st.subheader("Risk Metrics")

    c1, c2, c3 = st.columns(3)

    c1.metric("Profit Factor", f"{performance.profit_factor:.2f}")
    c2.metric("Expectancy", f"{performance.expectancy:.2f}")
    c3.metric("Max Drawdown", f"{performance.max_drawdown:.2f}")

    st.divider()

    # ==========================================================
    # TRADE QUALITY
    # ==========================================================

    st.subheader("Trade Quality")

    c1, c2, c3, c4 = st.columns(4)

    c1.metric("Average Win", f"{performance.average_win:.2f}")
    c2.metric("Average Loss", f"{performance.average_loss:.2f}")
    c3.metric("Largest Win", f"{performance.largest_win:.2f}")
    c4.metric("Largest Loss", f"{performance.largest_loss:.2f}")

    st.divider()

    # ==========================================================
    # EQUITY CURVE
    # ==========================================================

    st.subheader("Equity Curve")

    if performance.equity_curve:
        st.line_chart(performance.equity_curve)
    else:
        st.info("Equity curve not available.")