from dataclasses import dataclass, field
from enum import Enum


# ==========================================================
# Trade Direction
# ==========================================================

class SignalAction(Enum):

    BUY = "BUY"

    SELL = "SELL"

    HOLD = "HOLD"


# ==========================================================
# Strategy Signal
# ==========================================================

@dataclass(frozen=True)
class StrategySignal:
    """
    Output generated by any strategy.

    This object flows through the complete pipeline.
    """

    action: SignalAction

    strategy_name: str

    confidence: float

    reason: str

    quantity: int = 1

    stop_loss: float = 0.0

    target: float = 0.0

    metadata: dict = field(default_factory=dict)