from dataclasses import dataclass


@dataclass
class MarketContext:
    """
    Represents the current market state.
    Generated by MarketAnalyzer.
    """

    # =====================================================
    # REGIME
    # =====================================================

    regime: str = "UNKNOWN"

    bias: str = "NEUTRAL"

    # =====================================================
    # DEALER
    # =====================================================

    dealer: str = "UNKNOWN"

    gamma_state: str = "UNKNOWN"

    # =====================================================
    # VOLATILITY
    # =====================================================

    volatility: str = "NORMAL"

    atr: float = 0.0

    expected_move: float = 0.0

    # =====================================================
    # MARKET STRUCTURE
    # =====================================================

    pcr_bias: str = "UNKNOWN"

    institutional: str = "UNKNOWN"

    liquidity: str = "UNKNOWN"

    probability: int = 0

    # =====================================================
    # IMPORTANT LEVELS
    # =====================================================

    gamma_flip: float | None = None

    gamma_wall: float | None = None

    call_wall: float | None = None

    put_wall: float | None = None

    max_pain: float | None = None